<a href="https://colab.research.google.com/github/aso1801003/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### sklearnでエラーが出るので、前のバージョンを入れなおす

In [8]:
# ## 現在のscikit-leran えおcolabのVMからアンインストール
# !pip uninstall scikit-learn
# ## 前のバージョンを指定してVMにインストール
# !pip install scikit-learn==0.20 --ignore-installed

### all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [9]:
# ライブラリの読み込み
import pandas as pd
# 学習データとテスト検証用データを分割するライブラリ
from sklearn.model_selection import train_test_split
# 正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimators(推定期のすべてを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings

### WEBからアヤメのデータを読み込む

In [10]:
# urlリンクから読み込むライブラリ
import urllib.request as req
# url用の文字列変数を定義
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
# リンクから保存するためのファイルを定義
savefile = "iris.csv"
# requestクラスを使ってurlからでーたをsavefileへコピーして保存
req.urlretrieve(url, savefile)
# pandasのread_csvメソッドを使ってCSVファイルを読み込む
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### アヤメデータを目的変数：ｙと説明変数：ｘに分類する

In [11]:
y = iris_data.loc[:, "Name"] # 目的変数
x = iris_data.loc[:, ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"]] # 説明変数

print( y.head() )
print( x.head() )

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


In [12]:
# 学習用データ（train)とテスト検証用データ（test）に分離
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8, shuffle=True)
print(x_train.head())
print(x_train.head())
print(x_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
141          6.9         3.1          5.1         2.3
1            4.9         3.0          1.4         0.2
50           7.0         3.2          4.7         1.4
140          6.7         3.1          5.6         2.4
105          7.6         3.0          6.6         2.1
     SepalLength  SepalWidth  PetalLength  PetalWidth
141          6.9         3.1          5.1         2.3
1            4.9         3.0          1.4         0.2
50           7.0         3.2          4.7         1.4
140          6.7         3.1          5.6         2.4
105          7.6         3.0          6.6         2.1
     SepalLength  SepalWidth  PetalLength  PetalWidth
104          6.5         3.0          5.8         2.2
35           5.0         3.2          1.2         0.2
120          6.9         3.2          5.7         2.3
98           5.1         2.5          3.0         1.1
44           5.1         3.8          1.9         0.4


### allAlgorithmsにcclassifierを指定して「分類」でフィルターしたアルゴリズムの推定期群を取得する

In [13]:
# 水滴のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings('ignore')

### 推定期のリストをループしながら学習＆推論させる

In [16]:
# 推定器のリストをループ
for (name, algorithm) in allAlgorithms:
  # pythonでのtry-catch(try-except)
  try: # pythonのtry
    # 各アルゴリズムのオブジェクトを生成
    clf = algorithm() # 各アルゴリズムのクラスのコンストラクタを実行
    # 学習させる(fitメソッド)
    clf.fit(x_train, y_train)
    # 推論する
    y_pred = clf.predict(x_test)
    # accuracy_scoreで正解率を産出して表示
    print(name, "の正解率 = ", accuracy_score(y_test, y_pred))
  except Exception as e: #pythonのcatch(except)
    print("\033[31m" , " Error: \033[0m", name, ":" , e.args)
    # print("エラーです")
  else:
    # print("エラー以外")
    pass
# for終了

AdaBoostClassifier の正解率 =  0.9333333333333333
BaggingClassifier の正解率 =  0.9666666666666667
BernoulliNB の正解率 =  0.3
CalibratedClassifierCV の正解率 =  0.9333333333333333
CategoricalNB の正解率 =  1.0
  Error:  CheckingClassifier : ("could not convert string to float: 'Iris-virginica'",)
  Error:  ClassifierChain : ("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率 =  0.7
DecisionTreeClassifier の正解率 =  0.9666666666666667
DummyClassifier の正解率 =  0.36666666666666664
ExtraTreeClassifier の正解率 =  0.9333333333333333
ExtraTreesClassifier の正解率 =  0.9666666666666667
GaussianNB の正解率 =  0.9333333333333333
GaussianProcessClassifier の正解率 =  1.0
GradientBoostingClassifier の正解率 =  0.9666666666666667
HistGradientBoostingClassifier の正解率 =  0.9
KNeighborsClassifier の正解率 =  0.9666666666666667
LabelPropagation の正解率 =  0.9333333333333333
LabelSpreading の正解率 =  0.9666666666666667
LinearDiscriminantAnalysis の正解率 =  0.9666666666666667
LinearSVC の正解率 =  0.9333333333333333
Logistic

### クロスバリデーション

### クロスバリデーション関連のライブラリのインポート

In [15]:
# ライブラリのインポート
# 分割クロスバリデーション
from sklearn.model_selection import KFold
# クロスバリデーションスコアを取得す流ためのコード
from sklearn.model_selection import cross_val_score

### クロスバリデーションを実行する

In [17]:
# K分割考査検証
kfold_cv = KFold(n_splits=5, shuffle=True)
# すでに生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for( name, algorithms ) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    # scoreの属性がある学習モデルだけに絞る
    if hasattr( clf, "score" ):
      # クロスバリデーションをしてスコアを取得する
      scores = cross_val_score(clf,x,y, cv=kfold_cv)
      #　k=n_splits=5 回文のクロスバリデーションのスコアを表示
      print( name, "の正解率" )
      print( scores )
    # ifブロックの終了
  # tryブロックの終了
  except: # 例外処理ブロック
    # 何もしない
    pass

### おまけ:cross_val_scoreもっと詳しい結果を取得できる新しいクロスバリデーションオブジェクト:cross_validate

In [18]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

### cross_validateを使ったクロスバリデーション

In [19]:
# K分割考査検証
kfold_cv = KFold(n_splits=5, shuffle=True)
# すでに生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for( name, algorithms ) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    # scoreの属性がある学習モデルだけに絞る
    if hasattr( clf, "score" ):
      # クロスバリデーションをしてスコアを取得する
      scores = cross_validate(clf,x,y, cv=kfold_cv)
      #　k=n_splits=5 回文のクロスバリデーションのスコアを表示
      print( name, "の正解率" )
      print( scores )
    # ifブロックの終了
  # tryブロックの終了
  except: # 例外処理ブロック
    # 何もしない
    pass

### グリッドサーチ

In [20]:
from sklearn.model_selection import GridSearchCV
# SVCアルゴリズムの学習モデルをimport
from sklearn.svm import SVC

In [21]:
parameters = [
              # 3つのパラメータ、３パターン
              {"C":[1,10,100,1000],"kernel":["linear"]}, 
              {"C":[1,10,100,1000],"kernel":["rbf"], "gamma":[0.001,0.0001]}, 
              {"C":[1,10,100,1000],"kernel":["sigmoid"], "gamma":[0.001,0.0001]},
]

# 普通の学習
clf = SVC()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率 = ", accuracy_score(y_test, y_pred))

# グリッドサーチを行う
# K分割考査検証用のインスタンスを生成する
kfold_cv = KFold( n_splits=5, shuffle=True )
#　グリッドサーチのなかでK分割考査検証も行われる
clf_gird = GridSearchCV( SVC(), parameters, cv=kfold_cv )
clf_gird.fit(x_train, y_train)# 学習
# 学習ズミのモデルに最終的に設定されたパラメータを表示
print("最適なパラメーター　= ", clf_gird.best_estimator_)

# 最適なパラメーター設定ズミの学習モデルで評価
y_pred = clf_gird.predict(x_test)
print("グリッドサーチの正解率 = " , accuracy_score(y_test, y_pred))

普通の学習の正解率 =  1.0
最適なパラメーター　=  SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  1.0


### Numpyの動作確認

In [22]:
# import
import numpy as np

In [23]:
# numpy配列の初期化
a = np.array([1,2,3,4,5]) # numpy配列オブジェクトを生成
print(a)
# 型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [24]:
# 二次元のndarrayを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [25]:
# 配列の要素数を指定して０うめで初期化
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [26]:
# 配連番の配列を要素数を指定して初期化
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [27]:
# numpyで行列計算
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
print(x)
y = 3*x + 5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [30]:
# 配列の次元数を表示
a = np.array( [[1, 2, 3], [4, 5, 6]] )
print(a)
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [31]:
# Numpy配列で次元数を変換する
a = np.array([[1,2,3],[4,5,6]])
print("a=", a)
b = a.flatten()
print("b=", b)

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [32]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a) # 二次元配列の０行目
b = v[1:] #  一列目いこう
print(b)
c = v[:,0]
print(c)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
